server:
  port: 9001

spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncodeing=utf-8
    username: root
    password: 1234
  
  rabbitmq:
    host: 192.168.163.134

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #把自己的ip地址报告给Eureka(远程需要,本地测试没有问题)
    
myconfig:
  ip: 8.8.4.4
