server:
  port: 9007

spring:
  application:
    name: tensquare-search

  data:
    elasticsearch:
      #cluster-nodes: 127.0.0.1:9300
      cluster-nodes: 192.168.163.134:9300
      
    rabbitmq:
    host: 192.168.163.134

eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #把自己的ip地址报告给Eureka(远程需要,本地测试没有问题)